spring.datasource.url=jdbc:mysql://localhost:3307/netsit?serverTimezone=UTC&useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ASTERISK AMI
asterisk.ami.host=172.24.150.117
asterisk.ami.port=5038
asterisk.ami.username=springboot
asterisk.ami.password=${ASTERISK_AMI_PASSWORD:admin123}

#Servidor Python
netsit.python.url=http://127.0.0.1:5000
